
<!--  Modal content for the above example -->
<div id="term-condition" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Terms and Conditions </h4>
            </div>
            <div class="modal-body" style ="overflow :auto;">  
    <!--                            
				<div style ="text-align:center;"><b>WAMBI T & C</b>
				<br><u>Facility Employee</u>
				</div>
				<p><u>Terms and Conditions:</u></p>
				-->
				<p>&emsp;&emsp;<u>General:</u></p>
				<p>&emsp;&emsp;The contents of or on the Wambi.org site or portal (the “Site”), such as text, graphics, images, images obtained from Wambi’s licensors, and other material contained on the Wambi Site (“Content”) is for informational and survey purposes only.  </p>
				<p>&emsp;&emsp;<u> Use of Content:</u><p>
				<p>&emsp;&emsp;The Content is protected by copyright under both United States and foreign laws.  Title to the Content remains with Wambi, LLC or its licensors.  Any use of the Content not expressly permitted by these Terms and Conditions is a breach of these Terms and Conditions and may violate copyright, trademark, and other laws.  Content and features are subject to change or termination without notice in the editorial discretion of Wambi, LLC.  All rights not expressly granted herein are reserved to Wambi, LLC.  If you violate any of these Terms and Conditions, your permission to use the Content automatically terminates and you must immediately destroy any copies you have made of any portion of the Content.</p>
				<u>Liability of Wambi, LLC and Its Successors:</u></p>
				<p>&emsp;&emsp;The use of the Site and the Content is at your own risk.</p></p>
				<p>&emsp;&emsp;When using the Site, information will be transmitted over a medium that may be beyond the control and jurisdiction of Wambi, LLC and its suppliers.  Accordingly, Wambi, LLC assumes no liability for or relating to the delay, failure, interruption, or corruption of any data or other information transmitted in connection with use of the Site. </p>
				<p>&emsp;&emsp;The Site and the content are provided on an “as is” basis.  WAMBI, LLC, ITS LICENSORS, AND ITS SUPPLIERS, TO THE FULLEST EXTENT PERMITTED BY LAW, DISCLAIM ALL WARRANTIES, EITHER EXPRESS OR IMPLIED, STATUTORY OR OTHERWISE, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT OF THIRD PARTIES' RIGHTS, AND FITNESS FOR PARTICULAR PURPOSE.  </p>
				<p>&emsp;&emsp;In no event shall Wambi, LLC, its licensors, its suppliers, or any third parties mentioned on the Site be liable for any damages (including, without limitation, incidental and consequential damages, personal injury/wrongful death, lost profits, or damages resulting from lost data or business interruption) resulting from the use of or inability to use the Site or the Content, whether based on warranty, contract, tort, or any other legal theory, and whether or not Wambi, LLC, its licensors, its suppliers, or any third parties mentioned on the Site are advised of the possibility of such damages.  Wambi, LLC, its licensors, its suppliers, or any third parties mentioned on the Site shall be liable only to the extent of actual damages incurred by you, not to exceed U.S. $1000.  Wambi, LLC, its licensors, its suppliers, or any third parties mentioned on the Site are not liable for any personal injury, including death, caused by your use or misuse of the Site or Content.  Any claims arising in connection with your use of the Site or any Content must be brought within one (1) year of the date of the event giving rise to such action occurred. Remedies under these Terms and Conditions are exclusive and are limited to those expressly provided for in these Terms and Conditions.</p>
				<p><u>User Submissions:</u></p>
				<p>&emsp;&emsp;By submitting communications or content to the Site, you agree that such submission is non-confidential for all purposes.</p>
				<p>&emsp;&emsp;If you make any such submission you agree that you will not send or transmit to Wambi, LLC by email (including through the email addresses listed on the “Contact Us” page), any communication or content that infringes or violates any rights of any party. If you submit any business information, idea, concept or invention to Wambi, LLC by email, you agree such submission is non-confidential for all purposes.</p>
				<p>&emsp;&emsp;If you submit any business information, idea, concept or invention to Wambi, LLC by email, you automatically grant or warrant that the owner of such content or intellectual property has expressly granted Wambi, LLC a royalty-free, perpetual, irrevocable, world-wide nonexclusive license to use, reproduce, create derivative works from, modify, publish, edit, translate, distribute, perform, and display the communication or content in any media or medium, or any form, format, or forum now known or hereafter developed.  Wambi, LLC may sublicense its rights through multiple tiers of sublicenses.  <b>If you wish to keep any business information, ideas, concepts or inventions private or proprietary, do not submit them to Wambi, LLC by email.  We try to answer every email in a timely manner, but are not always able to do so.</b></p>
				<p><u>Passwords:</u></p>
				<p>&emsp;&emsp;You are responsible for taking all reasonable steps to ensure that no unauthorized person shall have access to your Wambi.org passwords or accounts.  It is your sole responsibility to (1) control the dissemination and use of sign-in name, screen name and passwords; (2) authorize, monitor, and control access to and use of your Wambi.org account and password; (3) promptly inform Wambi.org if you believe your account or password has been compromised or if there is any other reason you need to deactivate a password.  To send us an email, use the "Contact Us" links located at the bottom of every page of our Site.  You grant Wambi.org and all other persons or entities involved in the operation of the Site the right to transmit, monitor, retrieve, store, and use your information in connection with the operation of the Site.  Wambi, LLC cannot and does not assume any responsibility or liability for any information you submit, or your or third parties' use or misuse of information transmitted or received using Wambi, LLC tools and services.</p>
				<p><u>Indemnity:</u></p>
				<p>&emsp;&emsp;You agree to defend, indemnify, and hold Wambi, LLC, its officers, directors, employees, agents, licensors, and suppliers, harmless from and against any claims, actions or demands, liabilities and settlements including without limitation, reasonable legal and accounting fees, resulting from, or alleged to result from, your violation of these Terms and Conditions.</p>
				<p><u>Jurisdiction:</u></p>
				<p>&emsp;&emsp;You expressly agree that exclusive jurisdiction for any dispute with Wambi, LLC, or in any way relating to your use of the Site, resides in the courts of the State of Florida and you further agree and expressly consent to the exercise of personal jurisdiction in the courts of the State of Florida in connection with any such dispute including any claim involving Wambi, LLC or its affiliates, subsidiaries, employees, contractors, officers, directors, telecommunication providers, and content providers.</p>
				<p>&emsp;&emsp;These Terms and Conditions are governed by the internal substantive laws of the State of Florida, without respect to its conflict of laws principles.  If any provision of these Terms and Conditions is found to be invalid by any court having competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of these Terms and Conditions, which shall remain in full force and effect.  No waiver of any of these Terms and Conditions shall be deemed a further or continuing waiver of such term or condition or any other term or condition.</p>
				<p><u>Complete Agreement:</u></p>
				<p>&emsp;&emsp;These Terms and Conditions constitute the entire agreement between you and Wambi, LLC with respect to the use of the Site, and Content.</p>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->