DELETE FROM `carriers` ;
-- ----------------------------
-- Records of carriers
-- ----------------------------
INSERT INTO `carriers` VALUES ('1', '3 River Wireless', '@sms.3rivers.net');
INSERT INTO `carriers` VALUES ('2', 'ACS Wireless', '@paging.acswireless.com');
INSERT INTO `carriers` VALUES ('3', 'Alltel', '@message.alltel.com');
INSERT INTO `carriers` VALUES ('4', 'AT&T', '@txt.att.net');
INSERT INTO `carriers` VALUES ('5', 'Bell Canada', '@txt.bellmobility.ca');
INSERT INTO `carriers` VALUES ('6', 'Bell Canada', '@bellmobility.ca');
INSERT INTO `carriers` VALUES ('7', 'Bell Mobility (Canada)', '@txt.bell.ca');
INSERT INTO `carriers` VALUES ('8', 'Bell Mobility', '@txt.bellmobility.ca');
INSERT INTO `carriers` VALUES ('9', 'Blue Sky Frog', '@blueskyfrog.com');
INSERT INTO `carriers` VALUES ('10', 'Bluegrass Cellular', '@sms.bluecell.com');
INSERT INTO `carriers` VALUES ('11', 'Boost Mobile', '@myboostmobile.com');
INSERT INTO `carriers` VALUES ('12', 'BPL Mobile', '@bplmobile.com');
INSERT INTO `carriers` VALUES ('13', 'Carolina West Wireless', '@cwwsms.com');
INSERT INTO `carriers` VALUES ('14', 'Cellular One', '@mobile.celloneusa.com');
INSERT INTO `carriers` VALUES ('15', 'Cellular South', '@csouth1.com');
INSERT INTO `carriers` VALUES ('16', 'Centennial Wireless', '@cwemail.com');
INSERT INTO `carriers` VALUES ('17', 'CenturyTel', '@messaging.centurytel.net');
INSERT INTO `carriers` VALUES ('18', 'Cingular (Now AT&T)', '@txt.att.net');
INSERT INTO `carriers` VALUES ('19', 'Clearnet', '@msg.clearnet.com');
INSERT INTO `carriers` VALUES ('20', 'Comcast', '@comcastpcs.textmsg.com');
INSERT INTO `carriers` VALUES ('21', 'Corr Wireless Communications', '@corrwireless.net');
INSERT INTO `carriers` VALUES ('22', 'Dobson', '@mobile.dobson.net');
INSERT INTO `carriers` VALUES ('23', 'Edge Wireless', '@sms.edgewireless.com');
INSERT INTO `carriers` VALUES ('24', 'Fido', '@fido.ca');
INSERT INTO `carriers` VALUES ('25', 'Golden Telecom', '@sms.goldentele.com');
INSERT INTO `carriers` VALUES ('26', 'Helio', '@messaging.sprintpcs.com');
INSERT INTO `carriers` VALUES ('27', 'Houston Cellular', '@text.houstoncellular.net');
INSERT INTO `carriers` VALUES ('28', 'Idea Cellular', '@ideacellular.net');
INSERT INTO `carriers` VALUES ('29', 'Illinois Valley Cellular', '@ivctext.com');
INSERT INTO `carriers` VALUES ('30', 'Inland Cellular Telephone', '@inlandlink.com');
INSERT INTO `carriers` VALUES ('31', 'MCI', '@pagemci.com');
INSERT INTO `carriers` VALUES ('32', 'Metrocall', '@page.metrocall.com');
INSERT INTO `carriers` VALUES ('33', 'Metrocall 2-way', '@my2way.com');
INSERT INTO `carriers` VALUES ('34', 'Metro PCS', '@mymetropcs.com');
INSERT INTO `carriers` VALUES ('35', 'Microcell', '@fido.ca');
INSERT INTO `carriers` VALUES ('36', 'Midwest Wireless', '@clearlydigital.com');
INSERT INTO `carriers` VALUES ('37', 'Mobilcomm', '@mobilecomm.net');
INSERT INTO `carriers` VALUES ('38', 'MTS', '@text.mtsmobility.com');
INSERT INTO `carriers` VALUES ('39', 'Nextel', '@messaging.nextel.com');
INSERT INTO `carriers` VALUES ('40', 'OnlineBeep', '@onlinebeep.net');
INSERT INTO `carriers` VALUES ('41', 'PCS One', '@pcsone.net');
INSERT INTO `carriers` VALUES ('42', 'President\'s Choice', '@txt.bell.ca');
INSERT INTO `carriers` VALUES ('43', 'Public Service Cellular', '@sms.pscel.com');
INSERT INTO `carriers` VALUES ('44', 'Qwest', '@qwestmp.com');
INSERT INTO `carriers` VALUES ('45', 'Rogers AT&T Wireless', '@pcs.rogers.com');
INSERT INTO `carriers` VALUES ('46', 'Rogers Canada', '@pcs.rogers.com');
INSERT INTO `carriers` VALUES ('47', 'Satellink', '.pageme@satellink.net');
INSERT INTO `carriers` VALUES ('48', 'Southwestern Bell', '@email.swbw.com');
INSERT INTO `carriers` VALUES ('50', 'Sumcom', '@tms.suncom.com');
INSERT INTO `carriers` VALUES ('51', 'Surewest Communicaitons', '@mobile.surewest.com');
INSERT INTO `carriers` VALUES ('52', 'T-Mobile', '@tmomail.net');
INSERT INTO `carriers` VALUES ('53', 'Telus', '@msg.telus.com');
INSERT INTO `carriers` VALUES ('54', 'Tracfone', '@txt.att.net');
INSERT INTO `carriers` VALUES ('55', 'Triton', '@tms.suncom.com');
INSERT INTO `carriers` VALUES ('56', 'Unicel', '@utext.com');
INSERT INTO `carriers` VALUES ('57', 'U.S. Cellular', '@email.uscc.net');
INSERT INTO `carriers` VALUES ('58', 'Solo Mobile', '@txt.bell.ca');
INSERT INTO `carriers` VALUES ('59', 'Sprint', '@messaging.sprintpcs.com');
INSERT INTO `carriers` VALUES ('60', 'Sumcom', '@tms.suncom.com');
INSERT INTO `carriers` VALUES ('61', 'Surewest Communicaitons', '@mobile.surewest.com');
INSERT INTO `carriers` VALUES ('62', 'T-Mobile USA', '@tmomail.net');
INSERT INTO `carriers` VALUES ('67', 'US West', '@uswestdatamail.com');
INSERT INTO `carriers` VALUES ('68', 'Verizon Wireless', '@vtext.com');
INSERT INTO `carriers` VALUES ('69', 'Virgin Mobile', '@vmobl.com');
INSERT INTO `carriers` VALUES ('70', 'Virgin Mobile Canada', '@vmobile.ca');
INSERT INTO `carriers` VALUES ('71', 'West Central Wireless', '@sms.wcc.net');
INSERT INTO `carriers` VALUES ('72', 'Western Wireless', '@cellularonewest.com');
