<!--  Modal content for the above example -->
<div id="term-condition" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Términos y condiciones:</h4>
            </div>
            <div class="modal-body" style ="overflow :auto;">
              <!-- Content -->
                            <!--
                <div class ="text-center">Patient WAMBI T & C</div>
                <p><u>Terms and Conditions:</u></p>
-->

                <p>&emsp;&emsp;<u>General:</u></p>
                <p>&emsp;&emsp;El contenido del sitio o del portal Wambi.org (en adelante, el “Sitio”), como texto, gráficos, imágenes, imágenes obtenidas de los licenciatarios de Wambi y cualquier otro material contenido en el Sitio de Wambi (en adelante, el “Contenido”) es solo para propósitos informativos y de encuesta. Siempre solicite el asesoramiento del médico o de otro proveedor de atención médica calificado si tiene preguntas sobre una afección médica.</p>
                <p>&emsp;&emsp;<u>Niños:</u></p>
                <p>&emsp;&emsp;Este Sitio no está dirigido o diseñado para que lo utilicen niños menores de 13 años de edad. No recopilamos información de una persona que sabemos que es un niño menor de 13 años de edad.</p>
                <p>&emsp;&emsp;<u>Privacidad:</u></p>
                <p>&emsp;&emsp;Todos los datos recopilados de Wambi.org son para proporcionarles un mejor servicio a nuestros clientes en nuestra plataforma. Los datos que recopilamos incluyen datos sobre el momento en el que usted se inscribe, la información que proporciona y cómo interactúa con nuestra plataforma, incluidos los tipos de contenido que consulta y la frecuencia/duración de esas actividades, incluso con nuestros socios (servicios de publicidad) y el tráfico a sus sitios web y aplicaciones. </p>
                <p>&emsp;&emsp;No divulgamos su información personal a otras compañías, organizaciones o individuos fuera de Wambi, LLC, a menos que usted otorgue su consentimiento, con administradores de dominio, para procesamiento externo o por motivos legales. Es posible que divulguemos información que no lo identifique personalmente o información despersonalizada con nuestros socios, como pagadores, editores, publicistas o sitios relacionados. A pesar de que divulgaremos tendencias y realizaremos análisis a partir de la revisión de grandes muestras de datos, estos se recopilarán y se proporcionarán para mejorar nuestra plataforma y nuestros servicios, y para realizar investigaciones de mercado.</p>
                <p>&emsp;&emsp;<u>Uso del contenido:</u></p>
                <p>&emsp;&emsp;El Contenido está protegido por derechos de autor en virtud de las leyes de los Estados Unidos y de las leyes extranjeras. Wambi, LLC o sus licenciatarios siguen siendo los titulares del Contenido. Cualquier uso del Contenido que no se permita expresamente en estos Términos y condiciones es un incumplimiento de estos Términos y condiciones y puede violar los derechos de autor, de marca registrada y otras leyes. El Contenido y las características están sujetos a cambios o terminación sin necesidad de un previo aviso a discreción editorial de Wambi, LLC. Todos los derechos que, por la presente, no se otorgan expresamente están reservados a Wambi, LLC. Si viola cualquiera de estos Términos y condiciones, su autorización para utilizar el Contenido finaliza automáticamente y deberá destruir, de inmediato, toda copia que haya hecho de cualquier parte del Contenido. </p>
                <p>&emsp;&emsp;<u>Responsabilidad de Wambi, LLC y sus sucesores:</u></p>
                <p>&emsp;&emsp;El uso del Sitio y del Contenido se realiza bajo su propia responsabilidad. </p>
                <p>&emsp;&emsp;Cuando utilice el Sitio, la información se transmitirá a través de un medio que puede estar más allá del control y la jurisdicción de Wambi, LLC y sus proveedores. Por lo tanto, Wambi, LLC no asume ninguna responsabilidad por la demora, el fallo, la interrupción o la corrupción de cualquier dato o información transmitidos en relación con el uso del Sitio, o por cualquier problema vinculado con esto.</p>
                <p>&emsp;&emsp;El Sitio y el Contenido se proporcionan “como están”. WAMBI, LLC, SUS LICENCIATARIOS Y PROVEEDORES, EN LA MEDIDA QUE LO PERMITA LA LEY, EXCLUYEN TODA GARANTÍA, YA SEA EXPLÍCITA O IMPLÍCITA, LEGAL O DE OTRO TIPO, INCLUIDAS, ENTRE OTRAS, LAS GARANTÍAS IMPLÍCITAS DE COMERCIABILIDAD, DE NO INCUMPLIMIENTO DE DERECHOS DE TERCEROS Y DE APTITUD PARA UN PROPÓSITO EN PARTICULAR. </p>
                <p>&emsp;&emsp;Bajo ninguna circunstancia Wambi, LLC, sus licenciatarios, proveedores o terceros que se mencionen en el Sitio serán responsables de daños (incluidos, entre otros, daños accidentales y consiguientes, lesiones personales/muerte por negligencia, pérdida de ganancias o daños producidos a causa de datos perdidos o interrupción de negocios) que se produzcan por el uso del Sitio o del Contenido, o por la incapacidad de utilizarlos, ya sea que se basen en garantías, contratos, agravios o cualquier otra teoría legal y que Wambi, LLC, sus licenciatarios, proveedores o terceros que se mencionen en el Sitio estén informados de la posibilidad de dichos daños o no. Wambi, LLC, sus licenciatarios, proveedores o terceros que se mencionan en el Sitio serán responsables solo de los daños reales en los que usted haya incurrido, que no excedan los USD 1000. Wambi, LLC, sus licenciatarios, proveedores o terceros que se mencionan en el Sitio no son responsables de lesiones personales, incluida la muerte, producida por el uso o el uso incorrecto del Sitio o del Contenido. Cualquier demanda relacionada con el uso del Sitio o de cualquier Contenido debe presentarse dentro de un (1) año desde la fecha del evento que produjo dicha acción. Los recursos en virtud de estos Términos y condiciones son exclusivos y se limitan a aquellos expresamente contemplados en estos Términos y condiciones.</p>
                <p>&emsp;&emsp;<u>Envíos de usuarios:</u></p>
                <p>&emsp;&emsp;Si envía comunicaciones o contenido al Sitio, acepta que dicho envío no es confidencial a todos los efectos.</p>
                <p>&emsp;&emsp;Si realiza dicho envío, acepta que no enviará ni transmitirá comunicación o contenido alguno que infrinja o viole los derechos de cualquiera de las partes a Wambi, LLC por correo electrónico (incluida la dirección de correo electrónico mencionada en la página “Contacto”). Si envía cualquier información, idea, concepto o invento de negocios a Wambi, LLC por correo electrónico, acepta que dicho envío no es confidencial a todos los efectos.</p>
                <p>&emsp;&emsp;Si envía cualquier información, idea, concepto o invento de negocios a Wambi, LLC por correo electrónico, automáticamente autoriza o garantiza que el propietario de dicho contenido o propiedad intelectual le otorgó expresamente a Wambi, LLC una licencia gratuita, perpetua, irrevocable, mundial y no exclusiva para utilizar, reproducir, crear trabajos derivados, modificar, publicar, editar, traducir, distribuir, realizar y exponer la comunicación o el contenido en cualquier red o medio, o cualquier forma, formato o foro conocido actualmente o que se genere en el futuro. Wambi, LLC puede sublicenciar sus derechos en múltiples niveles de licencias secundarias. <b>Si desea mantener cualquier información, idea, concepto o invento de negocios privado o exclusivo, no los envíe a Wambi, LLC por correo electrónico. Intentamos responder a todos los correos electrónicos de forma oportuna, pero no siempre podemos hacerlo.</b></p>
                <p>&emsp;&emsp;<u>Contraseñas:</u></p>
                <p>&emsp;&emsp;Usted es responsable de tomar todas las medidas razonables para garantizar que ninguna persona no autorizada tenga acceso a sus contraseñas o a sus cuentas de Wambi.org. Es su exclusiva responsabilidad (1) controlar la difusión y el uso de su nombre de inicio de sesión, nombre de usuario y contraseñas; (2) autorizar, supervisar y controlar el acceso a su cuenta y a su contraseña de Wambi.org, y el uso de estas; (3) informar oportunamente a Wambi.org si cree que la seguridad de su cuenta o su contraseña está comprometida o si hay algún otro motivo por el que necesite desactivar una contraseña. Para enviarnos un correo electrónico, utilice los enlaces de “Contacto” ubicados en la parte inferior de cada página de nuestro Sitio. Le otorga a Wambi.org, y a todas las personas o entidades involucradas en el funcionamiento del Sitio, el derecho de transmitir, supervisar, recuperar, almacenar y utilizar su información en relación con el funcionamiento del Sitio. Wambi, LLC no asume ninguna responsabilidad por cualquier información que usted envíe, o por el uso o el uso incorrecto que usted o terceros hagan de la información transmitida o recibida por medio de las herramientas y los servicios de Wambi, LLC.</p>
                <p>&emsp;&emsp;<u>Indemnización:</u></p>
                <p>&emsp;&emsp;Acepta defender, indemnizar y eximir de toda responsabilidad a Wambi, LLC, a sus funcionarios, directores, empleados, agentes, licenciatarios y proveedores de cualquier reclamación, acción o demanda, responsabilidad y acuerdo, incluidos, entre otros, los honorarios jurídicos y contables razonables, que se produzcan por su violación de estos Términos y condiciones, o que sean resultado de esta.</p>
                <p>&emsp;&emsp;<u>Jurisdicción:</u></p>
                <p>&emsp;&emsp;Acepta expresamente que la jurisdicción exclusiva ante cualquier disputa con Wambi, LLC, o cualquier disputa relacionada de cualquier forma con su uso del Sitio, reside en los tribunales del Estado de Florida y, además, acepta y acuerda expresamente a emplear jurisdicción personal en los tribunales del Estado de Florida en relación con cualquier disputa de ese tipo, incluida cualquier demanda que involucre a Wambi, LLC o a sus filiales, subsidiarias, empleados, contratistas, funcionarios, directores, proveedores de telecomunicaciones y proveedores de contenido.</p>
                <p>&emsp;&emsp;Estos Términos y condiciones se rigen por las leyes sustantivas internas del Estado de Florida, no relacionadas con sus conflictos de principios legales. Si algún tribunal con jurisdicción competente descubre que cualquier disposición de estos Términos y condiciones es inválida, la invalidez de dicha disposición no afectará la validez del resto de las disposiciones de estos Términos y condiciones, que seguirán en plena vigencia. La renuncia a estos Términos y condiciones no se considerará como una renuncia adicional o continua de dicho término o condición, o de cualquier otro término o condición.</p>
                <p>&emsp;&emsp;<u>Acuerdo completo:</u></p>
                <p>&emsp;&emsp;Estos Términos y condiciones constituyen el acuerdo completo entre usted y Wambi, LLC en lo relacionado al uso del Sitio y del Contenido.</p>

            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->